---
title: "Getting and Cleaning Data Course Project: CodeBook"
author: "Brian Horst"
date: "12/16/2017"
output: md_document
---

This code book builds on those included in the UCI HAR Dataset (available from http://archive.ics.uci.edu/ml/machine-learning-databases/00240/) and describes:
* Where the data came from and a brief overview of the originating study
* Information about the variables (including units) in the data set not contained in the tidy data
* Information about the transformations made on the data
* Some other important tips

***
#Study
The data being used in this project comes from the University of California, Irvine (UCI), Human Activity Recognition (HAR) Using Smartphones Data Set. The data set was built by recording inertial sensor readings from a smartphone strapped to subjects as they performed various activities. A discussion of the original study may be found here: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones#

Per the information contained in the data set files, "The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

"The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details.

" For each record it is provided:
* Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
* Triaxial Angular velocity from the gyroscope. 
* A 561-feature vector with time and frequency domain variables. 
* Its activity label. 
* An identifier of the subject who carried out the experiment.

"Notes: 
* Features are normalized and bounded within [-1,1].
* Each feature vector is a row on the text file.
* The units used for the accelerations (total and body) are 'g's (gravity of earth -> 9.80665 m/seg2).
* The gyroscope units are rad/seg.

***
#Project CodeBook

##Source Data
The raw dataset available from UCI includes the following files:
*'README.txt': An overview of the dataset and the included files
*'features_info.txt': Shows information about the variables used on the feature vector
*'features.txt': List of all features
*'activity_labels.txt': Links the class labels with their activity name
*'train/X_train.txt': Training set
*'train/y_train.txt': Training labels
*'test/X_test.txt': Test set
*'test/y_test.txt': Test labels

The following files are available for the train and test data. Their descriptions are equivalent. 
*'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 
*'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 
*'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration. 
*'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second. 


##Files Used in the Project Analysis
This analysis made use of the following files:
* Common files
  + 'features.txt': a table of 561 row with 2 variables ('featuresID' and 'featuresName')
  + 'activity_labels.txt': a table of 6 rows and 2 variables ('activityID' and 'activityName')
* Test dataset files - 2947 observations for each of the following
  + 'test/subject_test.txt': single variable 'subject'
  + 'test/y_test.txt': single variable 'activityID'
  + 'test/X_test.txt': 561 variables representing various measurements
* Train data set files -  7352 observations for each of the following
  + 'train/subject_train.txt': single variable 'subject'
  + 'train/y_train.txt': single variable 'activityID'
  + 'train/X_train.txt': 561 variables representing various measurements

None of the files in the 'test/Inertial Signals' or 'train/Inertial Signals' folders were used.


##Details of the Transformation Performed by 'run_analysis.R' Script
The 'run_analysis.R' script performs the following functions:
0. Downloads the raw data.
* Checks to see if there is a directory to save data and working files in, and creates one if it does not already exist.
* Checks to see if the data has already been downloaded, and then downloads it from the URL specified in the ReadMe if necessary (https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip).
* Unzips the data set.

1. Merges the training and the test sets to create one data set.
* Each of the above tables were read using 'read.table'.
* The data tables read from 'X_test.txt' and 'X_train.txt' were assigned columns headers from the 'features.txt' 'featureName' variable.
* Test and train tables were created using 'cbind' using the corresponding subject, y, and X tables. Additionally, a group variable was added to indicate whether the oservations was from the "test" or "train" data set.
* The test and train tables were then combined using 'rbind' to create a complete dataset of 10299 rows of 564 variables.

(@) Extracts only the measurements on the mean and standard deviation for each measurement.
* A new table was created using only the subject, activityID, group, and a 'grep' search of the remaining variable to find only those that contained either "-mean(" or "-std(". (Note: the 'meanFreq' variables were intentionally not included, as they do not represent a mean or standard deviation of other measurements.)
* The resulting table contained 10299 rows of 69 variables.

(@) Uses descriptive activity names to name the activities in the data set
* The table created from 'activity_labels.txt' was used as a reference to replace the 'activityID' with the corresponding  descriptive 'activityName'.
* The variable in the data set was renamed to 'activity' to reflect that it was no longer an ID

(@) Appropriately labels the data set with descriptive variable names.
* A variable starting with "t"" or "f"" was changed to start with "time" or "freq"
* Non-alphanumeric characters were removed and the initial letters of the "mean" and "std" segments were capitalized.

(@) From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
* The 'dplyr' package was loaded.
* The data set was grouped by 'subject' and 'activity'.
* The mean for each variable for unique 'subject' and 'activity' pairs was calculated and stored in a new table with the corresponding 'subject' and 'activity' pairs.
* This resulted in a tidy table of 180 rows for 68 variables.


##Tidy Data Names
The resulting tidy table 'SubjectActivityAverage.txt' provides the average for each mean and standard deviation of measurements for a specific subject and activity.

* 'subject' is the individual who performed the activity and ranges from 1 to 30
* 'activity' consists of the 6 different activities that were performed
* 'time' indicates a "time domain" value
* 'freq' indicates a "frequency domain" value
* 'BodyAcc' indicates "Body Acceleration" 
* 'BodyGyro' indicates "Body Gyro"
* 'GravityAcc' indicates "Gravity Acceleration"
* 'Jerk' indicates a "Jerk" signal
* 'Mag' indicates "Magnitude"
* 'Mean' indicates a "mean" value
* 'Std' indicates a "standard deviation" value

The variable names in the resulting tidy data table are below. Included is the variable name from the original data.

Tidy Name | Raw Data Name
----------------------------- | ----------------------------- 
subject |
activity |
timeBodyAccMeanX | tBodyAcc-mean()-X
timeBodyAccMeanY | tBodyAcc-mean()-Y
timeBodyAccMeanZ | tBodyAcc-mean()-Z
timeBodyAccStdX | tBodyAcc-std()-X
timeBodyAccStdY | tBodyAcc-std()-Y
timeBodyAccStdZ | tBodyAcc-std()-Z
timeGravityAccMeanX | tGravityAcc-mean()-X
timeGravityAccMeanY | tGravityAcc-mean()-Y
timeGravityAccMeanZ | tGravityAcc-mean()-Z
timeGravityAccStdX | tGravityAcc-std()-X
timeGravityAccStdY | tGravityAcc-std()-Y
timeGravityAccStdZ | tGravityAcc-std()-Z
timeBodyAccJerkMeanX | tBodyAccJerk-mean()-X
timeBodyAccJerkMeanY | tBodyAccJerk-mean()-Y
timeBodyAccJerkMeanZ | tBodyAccJerk-mean()-Z
timeBodyAccJerkStdX | tBodyAccJerk-std()-X
timeBodyAccJerkStdY | tBodyAccJerk-std()-Y
timeBodyAccJerkStdZ | tBodyAccJerk-std()-Z
timeBodyGyroMeanX | tBodyGyro-mean()-X
timeBodyGyroMeanY | tBodyGyro-mean()-Y
timeBodyGyroMeanZ | tBodyGyro-mean()-Z
timeBodyGyroStdX | tBodyGyro-std()-X
timeBodyGyroStdY | tBodyGyro-std()-Y
timeBodyGyroStdZ | tBodyGyro-std()-Z
timeBodyGyroJerkMeanX | tBodyGyroJerk-mean()-X
timeBodyGyroJerkMeanY | tBodyGyroJerk-mean()-Y
timeBodyGyroJerkMeanZ | tBodyGyroJerk-mean()-Z
timeBodyGyroJerkStdX | tBodyGyroJerk-std()-X
timeBodyGyroJerkStdY | tBodyGyroJerk-std()-Y
timeBodyGyroJerkStdZ | tBodyGyroJerk-std()-Z
timeBodyAccMagMean | tBodyAccMag-mean()
timeBodyAccMagStd | tBodyAccMag-std()
timeGravityAccMagMean | tGravityAccMag-mean()
timeGravityAccMagStd | tGravityAccMag-std()
timeBodyAccJerkMagMean | tBodyAccJerkMag-mean()
timeBodyAccJerkMagStd | tBodyAccJerkMag-std()
timeBodyGyroMagMean | tBodyGyroMag-mean()
timeBodyGyroMagStd | tBodyGyroMag-std()
timeBodyGyroJerkMagMean | tBodyGyroJerkMag-mean()
timeBodyGyroJerkMagStd | tBodyGyroJerkMag-std()
freqBodyAccMeanX | fBodyAcc-mean()-X
freqBodyAccMeanY | fBodyAcc-mean()-Y
freqBodyAccMeanZ | fBodyAcc-mean()-Z
freqBodyAccStdX | fBodyAcc-std()-X
freqBodyAccStdY | fBodyAcc-std()-Y
freqBodyAccStdZ | fBodyAcc-std()-Z
freqBodyAccJerkMeanX | fBodyAccJerk-mean()-X
freqBodyAccJerkMeanY | fBodyAccJerk-mean()-Y
freqBodyAccJerkMeanZ | fBodyAccJerk-mean()-Z
freqBodyAccJerkStdX | fBodyAccJerk-std()-X
freqBodyAccJerkStdY | fBodyAccJerk-std()-Y
freqBodyAccJerkStdZ | fBodyAccJerk-std()-Z
freqBodyGyroMeanX | fBodyGyro-mean()-X
freqBodyGyroMeanY | fBodyGyro-mean()-Y
freqBodyGyroMeanZ | fBodyGyro-mean()-Z
freqBodyGyroStdX | fBodyGyro-std()-X
freqBodyGyroStdY | fBodyGyro-std()-Y
freqBodyGyroStdZ | fBodyGyro-std()-Z
freqBodyAccMagMean | fBodyAccMag-mean()
freqBodyAccMagStd | fBodyAccMag-std()
freqBodyBodyAccJerkMagMean | fBodyBodyAccJerkMag-mean()
freqBodyBodyAccJerkMagStd | fBodyBodyAccJerkMag-std()
freqBodyBodyGyroMagMean | fBodyBodyGyroMag-mean()
freqBodyBodyGyroMagStd | fBodyBodyGyroMag-std()
freqBodyBodyGyroJerkMagMean | fBodyBodyGyroJerkMag-mean()
freqBodyBodyGyroJerkMagStd | fBodyBodyGyroJerkMag-std()

